title: home
author: Haily Merritt
theme: minima
email: halamerr@iu.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Haily, a dual PHD student in Cognitive Science and Complex Systems at Indiana.

# social links
twitter_username: HailyMerritt # DO NOT include the @ character, or else the build will fail!
github_username:  h-merritt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
